# -*- coding: utf-8 -*-
"""SatAndGPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AmE8pVltgI48goyLvlyGIm4tFZWY0sDD
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
file_path = "https://raw.githubusercontent.com/ProfHan/ITEC4700/refs/heads/main/SAT_GPA.csv"
df = pd.read_csv(file_path)
GPA = df["GPA"]
SAT_Score = df["SAT Score"]
plt.figure(figsize=(8, 5))
plt.scatter(GPA, SAT_Score)
plt.xlabel("GPA")
plt.ylabel("SAT Score")
plt.title("Relationship between GPA and SAT scores")
plt.grid(True)
plt.show()
a,b = np.polyfit(GPA,SAT_Score, 1)
plt.plot(df["GPA"], a*df["GPA"] + b, color="red")
plt.scatter(df["GPA"], df["SAT Score"])
plt.xlabel("GPA")
plt.ylabel("SAT Score")
plt.title("Relationship between GPA and SAT scores")
plt.grid(True)
plt.show